/** Catalogue of rule ids (for `--list-rules` and the README). */
export const RULES: Record<string, string> = {
  'ctx-file-added': 'A new agent instruction file (AGENTS.md, CLAUDE.md, Cursor rule, SKILL.md ...) appeared.',
  'ctx-file-removed': 'An agent instruction file was deleted.',
  'ctx-section-added': 'A Markdown section was added to an instruction file.',
  'ctx-section-removed': 'A Markdown section was removed from an instruction file.',
  'ctx-section-changed': 'A Markdown section changed (line counts).',
  'ctx-guardrail-removed': 'A prohibition ("never", "do not", "must not" ...) was removed.',
  'ctx-frontmatter-changed': 'Frontmatter changed (tools, allowed-tools, alwaysApply, permissionMode ...).',
  'ctx-hidden-characters': 'Added text contains zero-width, bidi or Unicode tag characters.',
  'ctx-html-comment': 'Added HTML comment: invisible when rendered but read by agents.',
  'ctx-injection-phrase': 'Prompt-injection style phrasing was added ("ignore previous instructions", "do not tell the user").',
  'ctx-dangerous-command': 'Added instructions run risky commands (curl | sh, --no-verify, rm -rf /, --dangerously-skip-permissions).',
  'ctx-exfiltration': 'Added instructions ask to send data to an external URL.',
  'ctx-secret-literal': 'Added text contains something that looks like a credential.',
  'ctx-encoded-blob': 'Added text contains a long base64-like blob.',
  'ctx-url-added': 'URLs were added to an instruction file.',
  'mcp-server-added': 'A new MCP server was configured (new code execution or data egress surface).',
  'mcp-server-removed': 'An MCP server was removed.',
  'mcp-server-enabled': 'A previously disabled MCP server was enabled.',
  'mcp-server-disabled': 'An MCP server was disabled.',
  'mcp-command-changed': 'The command that launches an MCP server changed.',
  'mcp-args-changed': 'Arguments of an MCP server changed.',
  'mcp-package-changed': 'The npm/PyPI/Docker package an MCP server runs changed.',
  'mcp-url-changed': 'The endpoint of a remote MCP server changed.',
  'mcp-transport-changed': 'Transport (stdio/http/sse) changed.',
  'mcp-env-added': 'An environment variable was added to an MCP server.',
  'mcp-env-changed': 'An environment variable value changed (value never shown).',
  'mcp-env-removed': 'An environment variable was removed.',
  'mcp-header-added': 'An HTTP header was added to a remote MCP server.',
  'mcp-header-changed': 'An HTTP header value changed (value never shown).',
  'mcp-header-removed': 'An HTTP header was removed.',
  'mcp-auto-approve': 'Tools of an MCP server are auto-approved (autoApprove, alwaysAllow, trust).',
  'mcp-secret-literal': 'A literal credential is committed in an MCP config.',
  'mcp-unpinned-package': 'A package runner (npx, uvx, docker) launches an unpinned package.',
  'mcp-insecure-transport': 'Remote MCP server over plain http.',
  'mcp-shell-wrapper': 'MCP server launched through a shell -c wrapper (or a download-and-execute one-liner).',
  'mcp-enable-all': 'enableAllProjectMcpServers was turned on.',
  'mcp-server-approved': 'A project MCP server was pre-approved.',
  'perm-allow-added': 'A permission allow rule was added (severity depends on the breadth of the rule).',
  'perm-allow-removed': 'A permission allow rule was removed.',
  'perm-ask-added': 'A permission ask rule was added.',
  'perm-ask-removed': 'A permission ask rule was removed: the agent no longer prompts.',
  'perm-deny-added': 'A permission deny rule was added.',
  'perm-deny-removed': 'A permission deny rule was removed (guardrail).',
  'perm-directory-added': 'An additional directory was granted to the agent.',
  'perm-default-mode-changed': 'defaultMode changed (e.g. to bypassPermissions).',
  'hook-added': 'A hook (arbitrary command on agent events) was added.',
  'hook-removed': 'A hook was removed.',
  'settings-api-key-helper': 'apiKeyHelper changed.',
  'settings-env-added': 'An environment variable was added to every agent session.',
  'settings-env-changed': 'A session environment variable changed.',
  'settings-env-removed': 'A session environment variable was removed.',
  'settings-secret-literal': 'A literal credential is committed in agent settings.',
  'settings-base-url': 'ANTHROPIC_BASE_URL was overridden.',
  'config-unparsable': 'A tracked agent config is not valid JSON/JSONC.',
};
